// This data file stores all the courses offered at HSE, gives them ids, and assigns an image that correlates to its genre
import mathImg from "./images/math.png";
import globeImg from "./images/social.png";
import socialImg from "./images/social.png";
import bookImg from "./images/book.jpg";
import healthImg from "./images/health.jpeg";
import scienceImg from "./images/science.png";
import artsImg from "./images/arts.png";
import businessImg from "./images/business.jpg"; // For BUSINESS, MARKETING, AND IT
import computerImg from "./images/computer.jpg";
import agricultureImg from "./images/agriculture.png"; // For AGRICULTURE
import generalImg from "./images/general.jpg"; // For MULTIDISCIPLINARY and NONE
import familyScienceImg from "./images/family_science.png"; // For FAMILY AND CONSUMER SCIENCE
import engineeringImg from "./images/engineering.png"; // For ENGINEERING AND TECHNOLOGY
import pursuitImg from "./images/pursuit.png"; // For PURSUIT INSITUTE
import languageImg from "./images/language.png"; // For WORLD LANGUAGES

export const courses = [
    // MATHEMATICS
    { id: 2520, title: "Algebra I", img: mathImg, genre: "MATHEMATICS" },
    { id: 2516, title: "Algebra I Lab", img: mathImg, genre: "MATHEMATICS" },
    { id: 2532, title: "Geometry", img: mathImg, genre: "MATHEMATICS" },
    { id: 2532, title: "Geometry, Honors", img: mathImg, genre: "MATHEMATICS" },

    // PE & HEALTH
    { id: 3506, title: "Health and Wellness Education", img: healthImg, genre: "PE & HEALTH" },
    { id: 3542, title: "Physical Education I", img: healthImg, genre: "PE & HEALTH" },
    { id: 3544, title: "Physical Education II", img: healthImg, genre: "PE & HEALTH" },
    { id: 3500, title: "Advanced Health Education - Sports Medicine II", img: healthImg, genre: "PE & HEALTH" },
    { id: 3500, title: "Advanced Health Education - Sports Medicine I", img: healthImg, genre: "PE & HEALTH" },
    { id: 3560, title: "Elective Physical Education - Co-ed Recreational Games", img: healthImg, genre: "PE & HEALTH" },
    { id: 3560, title: "Elective Physical Education - Intro to Weight Training", img: healthImg, genre: "PE & HEALTH" },
    { id: 3560, title: "Elective Physical Education - Advanced Physical Conditioning", img: healthImg, genre: "PE & HEALTH" },
    { id: 3560, title: "Elective Physical Education - Lifeguarding", img: healthImg, genre: "PE & HEALTH" },
    { id: 3542, title: "Alternative Physical Education Credit", img: healthImg, genre: "PE & HEALTH" },

    // SCIENCE
    { id: 3024, title: "Biology I", img: scienceImg, genre: "SCIENCE" },
    { id: 3024, title: "Biology I Honors", img: scienceImg, genre: "SCIENCE" },
    { id: 3064, title: "Chemistry I", img: scienceImg, genre: "SCIENCE" },
    { id: 3064, title: "Chemistry I Honors", img: scienceImg, genre: "SCIENCE" },
    { id: 3044, title: "Earth and Space Science", img: scienceImg, genre: "SCIENCE" },
    { id: 3108, title: "Integrated Chemistry Physics (ICP)", img: scienceImg, genre: "SCIENCE" },
    { id: 3084, title: "Physics I", img: scienceImg, genre: "SCIENCE" },
    { id: 3084, title: "Physics I Honors", img: scienceImg, genre: "SCIENCE" },
    { id: 5276, title: "Anatomy and Physiology", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Genetics", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Microbiology", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Zoology", img: scienceImg, genre: "SCIENCE" },
    { id: 3066, title: "Chemistry II", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Principles of Organic and Biochemistry", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Astronomy I", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Astronomy II", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Geology", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Meteorology", img: scienceImg, genre: "SCIENCE" },
    { id: 3092, title: "Advanced Science, Special Topics, Forensic Science", img: scienceImg, genre: "SCIENCE" },
    { id: 3090, title: "Advanced Science, College Credit - Anatomy/Physiology", img: scienceImg, genre: "SCIENCE" },
    { id: 3020, title: "AP Biology", img: scienceImg, genre: "SCIENCE" },
    { id: 3060, title: "AP Chemistry", img: scienceImg, genre: "SCIENCE" },
    { id: 3090, title: "Advanced Science, College Credit, Elementary Chemistry I-ACP Chemistry", img: scienceImg, genre: "SCIENCE" },
    { id: 3012, title: "AP Environmental Science", img: scienceImg, genre: "SCIENCE" },
    { id: 3088, title: "AP Physics C", img: scienceImg, genre: "SCIENCE" },
    { id: 3090, title: "Advanced Science, College Credit, Physics-ACP Physics", img: scienceImg, genre: "SCIENCE" },
    { id: 5218, title: "Principles of Biomedical Sciences", img: scienceImg, genre: "SCIENCE" },
    { id: 5216, title: "Human Body Systems", img: scienceImg, genre: "SCIENCE" },
    { id: 5217, title: "Medical Interventions", img: scienceImg, genre: "SCIENCE" },
    { id: 5219, title: "Biomedical Innovation", img: scienceImg, genre: "SCIENCE" },

    // PERFORMING ARTS
    { id: 4146, title: "Dance Performance", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4142, title: "Dance Choreography", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4206, title: "Music History and Appreciation", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4208, title: "Music Theory and Composition", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4210, title: "AP Music Theory", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4166, title: "Beginning Orchestra/Camerata Orchestra", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4172, title: "Intermediate Orchestra/Philharmonic Orchestra", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4174, title: "Advanced Orchestra/Symphony Orchestra", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4160, title: "Beginning Concert Band/Concert Band Blue (01)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4168, title: "Intermediate Concert Band/Symphonic Band", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4170, title: "Advanced Concert Band/Wind Symphony", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4170, title: "Advanced Concert Band/Wind Ensemble", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4164, title: "Jazz Ensemble", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4162, title: "Instrumental Ensemble: Percussion", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4204, title: "Piano and Electronic Keyboard/Beginning", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4204, title: "Piano and Electronic Keyboard/Intermediate", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4182, title: "Beginning Chorus/Royal Vocals (open to female students)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4182, title: "Beginning Chorus - Royal Vocals", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4186, title: "Intermediate Chorus/Royal Singers (mixed ensemble)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4186, title: "Intermediate Chorus - Accents", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4188, title: "Advanced Chorus/Royal Sensation (open to female students)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4188, title: "Advanced Chorus/Royal Edition (mixed ensemble)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4244, title: "Technical Theater", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4252, title: "Technical Theater II", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4242, title: "Theatre Arts/Acting I", img: artsImg, genre: "PERFORMING ARTS" },

    // VISUAL ARTS
    { id: 4060, title: "Drawing I: Observational Drawing", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4060, title: "Drawing II", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4060, title: "Drawing III: Figure Drawing", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4060, title: "Drawing IV", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4064, title: "Painting I", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4064, title: "Painting II", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4086, title: "Visual Communications I", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4086, title: "Visual Communications II", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4062, title: "Photography I: DSLR", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4062, title: "Photography II", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4066, title: "Printmaking", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4040, title: "Hand Building: Ceramics", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4040, title: "Wheel Throwing: Ceramics", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4040, title: "Ceramics III: Advanced", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4042, title: "Jewelry I: Metalsmithing", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4042, title: "Jewelry II: Metalsmithing", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4044, title: "Sculpture I", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4044, title: "Sculpture II", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4004, title: "Peer Art Education", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4048, title: "AP Drawing", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4050, title: "AP 2-D Art and Design Portfolio", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4052, title: "AP 3-D Art and Design Portfolio", img: artsImg, genre: "VISUAL ARTS" },
    { id: 4025, title: "AP Art History", img: artsImg, genre: "VISUAL ARTS" },

    // SOCIAL STUDIES
    { id: 1570, title: "Geography and History of the World", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1548, title: "World History and Civilization", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1576, title: "AP World History Modern", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1572, title: "AP Human Geography", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1526, title: "Law Education", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1512, title: "Current Issues and Events", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1542, title: "U.S. History", img: socialImg, genre: "SOCIAL STUDIES" },
    { id: 1534, title: "Sociology", img: socialImg, genre: "SOCIAL STUDIES" },

    // SOCIAL STUDIES
    { id: 1562, title: "AP U.S. History", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1574, title: "Advanced Social Studies, College Credit - ACP American History I & II", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1556, title: "AP European History", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1538, title: "Topics in History - Global Studies", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1516, title: "Ethnic Studies", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1538, title: "Topics in History - Comparative Religions", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1538, title: "Topics in History - Constitutional Law", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1518, title: "Indiana Studies", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1532, title: "Psychology", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1558, title: "AP Psychology", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1540, title: "U.S. Government", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1560, title: "AP U.S. Government & Politics - We the People", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1560, title: "AP U.S. Government & Politics", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1574, title: "Advanced Social Sciences, College Credit - ACP Government (Y103)", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1552, title: "AP Comparative Government and Politics", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1514, title: "Economics", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1566, title: "Advanced Placement Microeconomics", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1564, title: "Advanced Placement Macroeconomics", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: 1500, title: "African Studies", img: globeImg, genre: "SOCIAL STUDIES" },
    { id: "N/A", title: "Law and Government Academy", img: globeImg, genre: "SOCIAL STUDIES" },

    // MATHEMATICS
    { id: 2522, title: "Algebra II", img: mathImg, genre: "MATHEMATICS" },
    { id: 2522, title: "Algebra II, Honors", img: mathImg, genre: "MATHEMATICS" },
    { id: 2544, title: "Advanced Math, College Credit - College Algebra", img: mathImg, genre: "MATHEMATICS" },
    { id: 2524, title: "Analytical Algebra II", img: mathImg, genre: "MATHEMATICS" },
    { id: "2564/2566", title: "AP PRE-CALCULUS AB; FORMALLY KNOWN AS PRE-CALCULUS & TRIGONOMETRY", img: mathImg, genre: "MATHEMATICS" },
    { id: "2564/2566", title: "AP PRE-CALCULUS BC; FORMALLY KNOWN AS HONORS PRE-CALCULUS & TRIGONOMETRY", img: mathImg, genre: "MATHEMATICS" },
    { id: 2546, title: "Probability and Statistics", img: mathImg, genre: "MATHEMATICS" },
    { id: 4512, title: "Business Mathematics", img: mathImg, genre: "MATHEMATICS" },
    { id: 2550, title: "Quantitative Reasoning", img: mathImg, genre: "MATHEMATICS" },
    { id: 2570, title: "Advanced Placement Statistics", img: mathImg, genre: "MATHEMATICS" },
    { id: 2544, title: "Brief Survey of Calculus (ACP/IU M119)", img: mathImg, genre: "MATHEMATICS" },
    { id: 2562, title: "AP / ACP Calculus AB (ACP M211)", img: mathImg, genre: "MATHEMATICS" },
    { id: 2572, title: "AP / ACP Calculus BC (ACP M211 & M212)", img: mathImg, genre: "MATHEMATICS" },
    { id: 2544, title: "ACP Finite Math (ACP M118)", img: mathImg, genre: "MATHEMATICS" },
    { id: 2544, title: "Multivariable Calculus and its Applications - Ball State", img: mathImg, genre: "MATHEMATICS" },
    { id: 2544, title: "Differential Equations - Ball State", img: mathImg, genre: "MATHEMATICS" },

    // WORLD LANGUAGES
    { id: 2020, title: "French I", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2120, title: "Spanish I", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2040, title: "German I", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: "2190/2192", title: "Language for Heritage Speakers I and II", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2022, title: "French II", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2022, title: "French II, Honors", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2122, title: "Spanish II, Honors", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2042, title: "German II, Honors", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2122, title: "Spanish II", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2042, title: "German II", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2156, title: "American Sign Language I", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2158, title: "American Sign Language II", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2024, title: "Ivy Tech French 101-102 (French III)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2124, title: "Ivy Tech 101-102 (Spanish III)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2044, title: "German III", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2024, title: "Ivy Tech French 101-102 (French III Honors)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2124, title: "Ivy Tech Spanish 101-102 (Spanish III, Honors)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2044, title: "German III, Honors", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2126, title: "Ivy Tech Spanish 201 (Spanish IV)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2046, title: "German IV ACP German 250 through Indiana University", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2026, title: "Ivy Tech French 201-202 (French IV/IV Honors)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2126, title: "Ivy Tech Spanish 201-202 (Spanish IV Honors)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2046, title: "German IV, Honors ACP German 250 through Indiana University", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2028, title: "French V", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2128, title: "Ivy Tech Spanish 202 (Spanish V)", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2048, title: "German V", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2032, title: "Advanced Placement French", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2132, title: "Advanced Placement Spanish", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: 2052, title: "Advanced Placement German", img: languageImg, genre: "WORLD LANGUAGES" },
    { id: "N/A", title: "Alternative World Language Credit", img: languageImg, genre: "WORLD LANGUAGES" },

    // MULTIDISCIPLINARY
    { id: 520, title: "Peer Tutoring: Special Needs", img: generalImg, genre: "MULTIDISCIPLINARY" },

    // ENGLISH/LANGUAGE ARTS
    { id: 1002, title: "English 9", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1002, title: "Honors English 9", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1004, title: "English 10", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1004, title: "Honors English 10", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1006, title: "English 11", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1008, title: "English 12", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1058, title: "AP Literature and Composition", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1056, title: "AP English Language and Composition", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1006, title: "AP Seminar", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1008, title: "AP Research", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1124, title: "ACP Composition – College Credit, Reading, Writing, & Inquiry (ACP/IU W131)", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1124, title: "Advanced English/Language Arts – College Credit, Literary Interpretation (ACP/IU L202)", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1008, title: "English 12 Dual Credit", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1026, title: "Classical Literature", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1028, title: "Dramatic Literature", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1036, title: "Genres of Literature - Gothic/Horror", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1036, title: "Genres of Literature - Science Fiction", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1036, title: "Genres of Literature - Young Adult Literature", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1048, title: "Themes in Literature - Female Authors", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1048, title: "Themes in Literature - Lean In: Female Leadership through Multimedia Studies", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1048, title: "Themes in Literature - Literature in Life & Sports", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1048, title: "Themes in Literature - War Literature", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },

    // MEDIA ARTS & COMMUNICATIONS
    { id: 1092, title: "Creative Writing", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1076, title: "Speech", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1070, title: "Debate", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1084, title: "Digital Media", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1080, title: "Journalism", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1080, title: "Sports Journalism", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1036, title: "Genres of Literature - Leadership & Legacy", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1010, title: "Literacy Lab 9/10 and 11/12", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 2188, title: "English as a New Language", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: "1002,1004,1006,1008", title: "English 9/10/11/12 (ENL)", img: bookImg, genre: "MEDIA ARTS & COMMUNICATIONS" },

    // COMPUTER SCIENCE
    { id: 4568, title: "AP Computer Science Principles", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 7185, title: "Website and Database Development", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 4570, title: "AP Computer Science A (Java)", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 7253, title: "Software Development Capstone", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 5238, title: "Advanced Career and Technical Education College Credit", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 7184, title: "Software Development", img: computerImg, genre: "COMPUTER SCIENCE" },
    { id: 7180, title: "Information Technology Fundamentals", img: computerImg, genre: "COMPUTER SCIENCE" },

    // AGRICULTURE
    { id: 7177, title: "Principles of Agriculture", img: agricultureImg, genre: "AGRICULTURE" },
    { id: 5070, title: "Advanced Life Science: Animals", img: agricultureImg, genre: "AGRICULTURE" },
    { id: 5008, title: "Animal Science", img: agricultureImg, genre: "AGRICULTURE" },
    { id: 5088, title: "Agricultural Power Structure And Technology (Welding)", img: agricultureImg, genre: "AGRICULTURE" },
    { id: 5228, title: "Supervised Agricultural Experience", img: agricultureImg, genre: "AGRICULTURE" },
    { id: 5170, title: "Plant and Soil Science", img: agricultureImg, genre: "AGRICULTURE" },

    // MULTIDISCIPLINARY
    { id: 530, title: "Career Exploration Internship", img: generalImg, genre: "MULTIDISCIPLINARY" },
    { id: 5394, title: "Preparing for College and Careers", img: generalImg, genre: "MULTIDISCIPLINARY" },

    // FAMILY AND CONSUMER SCIENCE
    { id: 5342, title: "Nutrition And Wellness (Senior Foods)", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 5364, title: "Interpersonal Relationships", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7161, title: "Principles of Teaching (Cadet Teaching)", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7160, title: "Principles of Early Childhood Education (Formerly Child Development)", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7158, title: "Early Childhood Education Curriculum", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7159, title: "Early Childhood Education Guidance", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7259, title: "Early Childhood Education Capstone", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7173, title: "Principles of Culinary & Hospitality", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7171, title: "Nutrition", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7301, title: "Principles of Fashion and Textiles", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },
    { id: 7132, title: "Principles of Interior Design", img: familyScienceImg, genre: "FAMILY AND CONSUMER SCIENCE" },

    // ENGINEERING AND TECHNOLOGY
    { id: 4802, title: "Introduction to Engineering Design", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5644, title: "Principles of Engineering", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5538, title: "Digital Electronics", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5534, title: "Computer Integrated Manufacturing", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5650, title: "Civil Engineering and Architecture", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5698, title: "Engineering Design and Development", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 7199, title: "Engineering Essentials", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5580, title: "Construction Trades I and II", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },
    { id: 5518, title: "Aerospace Engineering", img: engineeringImg, genre: "ENGINEERING AND TECHNOLOGY" },

    // BUSINESS, MARKETING, AND IT
    { id: 4540, title: "Personal Financial Responsibility", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4524, title: "Accounting Fundamentals", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4562, title: "Principles of Business Management", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5914, title: "Marketing Fundamentals", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5967, title: "Introduction to Entrepreneurship", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4562, title: "Advanced Business, College Credit, Business Administration-IU X100 (Principles Of Business Management)", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5258, title: "Finance & Investment - Banking and Credit", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5258, title: "Finance and Investment- Securities and Insurance", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4564, title: "Advanced Business, College Credit, Finance and International Business, University Of Indianapolis", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4564, title: "Advanced Business, College Credit, Accounting, Anderson University", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5260, title: "Work Based Learning: Business And Marketing (Finance Academy Internship)", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4522, title: "Advanced Accounting", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 5258, title: "Finance & Investment", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 7143, title: "Management Fundamentals", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 7154, title: "Digital Marketing (The Fan Stand)(11 – spring semester; 12 – fall semester)", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 7183, title: "Principles of Computing", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 7181, title: "Networking and Cybersecurity Operations", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4565, title: "Computing Foundations For a Digital Age", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 7154, title: "Digital Marketing", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },

    // PURSUIT INSITUTE
    { id: "7165, 5274, 7168", title: "Emergency Medical Technician", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7166, 5274, 7168", title: "Certified Nursing Assistant Preparation", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7164, 5274, 7168", title: "Medical Assisting", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7139, 7306", title: "Music and Sound Production", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7110, 7111", title: "Welding I", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117, 5088, 7112, 7228", title: "Ag Mechanical and Engineering", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117,5008,5070,7262", title: "Agri Science", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117,5132,7114,7232", title: "Horticulture", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117,5132,7115,7234", title: "Landscaping", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117,5180,7271,7262", title: "Natural Resources", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7161,7157,7162,7267", title: "Education Professions", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7168,5274,7164,7255", title: "Certified Clinical Medical Assistant (CCMA)", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7315,7316,7317,7318", title: "Dental Careers", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7168,5274,7167,7310", title: "Pharmacy", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7168,5274,7166,7255", title: "Pre-Nursing", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7183,7179,7178,7243", title: "Cybersecurity", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7175,7331,7332,7334", title: "Cosmetology", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7213,7205,7212,7375", title: "Automotive Services", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7280, 7281, 5070, 7282", title: "Veterinary Science", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7168, 5274, 7163, 7257", title: "Surgical Technican", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7214, 7217, 7207", title: "Aviation Management", img: pursuitImg, genre: "PURSUIT INSITUTE" },
    { id: "7117, 7116, 7113, 7236, 7238", title: "Precision Agriculture", img: pursuitImg, genre: "PURSUIT INSITUTE" },

    // MEDIA ARTS & COMMUNICATIONS
    { id: 1086, title: "Student Media", img: artsImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1034, title: "Film Literature", img: artsImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 1124, title: "Advanced English/Language Arts, College Credit-Public Speaking (ACP/IU S121)", img: artsImg, genre: "MEDIA ARTS & COMMUNICATIONS" },
    { id: 590, title: "Innovations I and II", img: artsImg, genre: "MEDIA ARTS & COMMUNICATIONS" },

    // NONE
    { id: "none", title: "Study Hall", img: generalImg, genre: "NONE" },

    // SCIENCE
    { id: 3044, title: "Earth and Space Science - PBL", img: scienceImg, genre: "SCIENCE" },
    { id: 3108, title: "Integrated Chemistry and Physics (ICP) – PBL", img: scienceImg, genre: "SCIENCE" },
    { id: 3024, title: "Biology I PBL", img: scienceImg, genre: "SCIENCE" },
    { id: 3012, title: "AP Environmental Science PBL", img: scienceImg, genre: "SCIENCE" },

    // ENGLISH/LANGUAGE ARTS
    { id: 1124, title: "Advanced English/Language Arts, College Credit-Discovering Literature (ACP/IU L111)", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1008, title: "English 12 Dual Credit (Ivy Tech ENGL 111)", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1032, title: "Ethnic Literature", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 1040, title: "Literary Movements: Modernism to Contemporary", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },
    { id: 520, title: "Peer Tutoring: Writing Mentor", img: bookImg, genre: "ENGLISH/LANGUAGE ARTS" },

    // PERFORMING ARTS
    { id: 4174, title: "Advanced Orchestra/Serenata Orchestra", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4160, title: "Beginning Concert Band/Concert Band White (02)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4186, title: "Intermediate Chorus/Accents (open to female students)", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4146, title: "Dance Performance: Color Guard", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4202, title: "Electronic Music", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4240, title: "Advanced Theatre Arts/Acting II", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4240, title: "Advanced Theatre Arts/Acting III", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4240, title: "Advanced Theatre Arts/Acting IV", img: artsImg, genre: "PERFORMING ARTS" },
    { id: 4254, title: "Theater Arts-Special Topics", img: artsImg, genre: "PERFORMING ARTS" },

    // SOCIAL STUDIES
    { id: 590, title: "AP African American Studies", img: socialImg, genre: "SOCIAL STUDIES" },

    // WORLD LANGUAGES
    { id: 0, title: "American Sign Language III", img: languageImg, genre: "WORLD LANGUAGES" },

    // BUSINESS, MARKETING, AND IT
    { id: 4528, title: "Digital Applications and Responsibility", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
    { id: 4578, title: "Business Computing & Data Analytics", img: businessImg, genre: "BUSINESS, MARKETING, AND IT" },
];